### ISSUE TITLE
Second hyphen in some Packard codes?

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/packard#1]
It’s apparent from the LXX module that many Packard morph codes used in the wild contain a second hyphen.

How did these originate?

Will your script address these?

**Comment by pierre-amadio** [comment]
No idea.
Do you have a specific verse where there is such a double hyphen code ?

**Comment by DavidHaslam** [comment]
My **Excel™** file aligns all the extracted **Packard** codes against those from the **LXX** module.

[Packard vs LXX.xlsx](https://github.com/pierre-amadio/packard/files/6037093/Packard.vs.LXX.xlsx)

### Notes
1. The worksheet is protected, albeit without a password, merely to prevent inadvertent changes.
2. **Autofilter** is allowed while it's protected. Use this feature to locate codes containing a hyphen.
3. **Scripture references** are not included, given the nature of the extracted data. **Hint:** _Use search_.
4. The title cells & a few others have comments.
5. There are 2 or 3 codes in the **LXX** that look like something _other_ than morphology.

**Comment by pierre-amadio** [comment]
Hmm.i m not quite sure what to do with that xls file :-)
I plan to make a list of all code that actually is present in the latest LXX module, and prepare the dictionnary based on that list (i am not aware of any other strong module using the packard morph code)
I did not find yet any weird entry.I ll see what i can do once i see one.If you know a specific verse where there is such an entry, let me know.

**Comment by DavidHaslam** [comment]
I should have noted that
- **LXX** is version 2.5
- **LXX_th** is version 2.6

Maybe you didn't play with the **AutoFilter**, which was saved with one set for the **Difference** column being _nonzero_?

Here's a [screenshot](https://www.dropbox.com/s/vl6ycnu5ipwwwnp/Screenshot%202021-02-24%2018.45.54.png?dl=0) with a different filter. 

It's evident that these two "Charlies" are not **Packard** codes but **betacodes** in the wrong place!

The locations in both modules are:

- **II Chronicles 30:22** which has `<w lemma="strong:G4895" morph="packard:V)@PAPGP">συνιοντων</w>`
- **Psalms 150:5** which has `<w lemma="strong:G2@GSM" morph="packard:2@GSM">αλαλαγμου</w>`

I also wonder about this one (_not in the screenshot_)
- **Nehemiah 3:25** which has `<w lemma="strong:G511" morph="packard:A-1ACNSM">ανωτερος</w>`
I'm puzzled about the code `A-1ACNSM` as to how it matches anything in the documentation. It's also the sole instance containing `CN` in the whole module. However, the Greek word `ανωτερος` is a _hapax legomenon_, so I shouldn't be so surprised.

**Comment by DavidHaslam** [comment]
I've not begun to look yet, but it's conceivable that your own latest **LXX** module is one with those two errors fixed.

**Comment by DavidHaslam** [comment]
## Double hyphens
Out of a total of 580 _unique_ morph codes (ignoring the _counts_ of each)
- 48 contain `-1` 
- 39 contain `-2`
- 80 contain `-3`

These all end with either `S` or `P` and they all have two hyphens. 

My analysis was performed (_as usual_) on the output of **mod2imp** directed to a text file.

**Comment by DavidHaslam** [comment]
Just started to look at the **extracted counts** of the **packard** morph codes comparing **LXX** version **2.6** with latest **beta** version **3.0** module based upon your data.

Here are the **tab delimited** packard count files compressed using **7-Zip**.
### v2.5 
[LXX.raw.imp.packard.count.tab.zip](https://github.com/pierre-amadio/packard/files/6039049/LXX.raw.imp.packard.count.tab.zip)
### v3.0
[LXX.raw.imp.packard.count.tab.zip](https://github.com/pierre-amadio/packard/files/6039051/LXX.raw.imp.packard.count.tab.zip)

It's quite evident that there's been a **major overhaul** between these two module versions.
- **v2.5** has 0579 unique codes
- **v3.0** has 2857 unique codes

936 of these end with text matching the regex `[123][SP]` but **none** of these have a **hyphen** before the digit.

**Comment by DavidHaslam** [comment]
The main issue then becomes, 

> Who inserted all those second hyphens in the source used to make the earlier version?

Or alternatively,

> Was there a deliberate deletion of second hyphens at some time between the two sets of data?

cf. CrossWire dictionary module **Packard** version 1.4 has this change:
```
History_1.4=(2021-02-23) Inserted a second hyphen in specified $$$ keys to match more keys in module LXX
```
If there are to be _no_ second hyphens, then these _recently added_ second hyphens in the **Packard** module must now be deleted!

**Comment by DavidHaslam** [comment]
btw. The **STEP Bible** module **LXX_th** (currently v3.0) has the morphology codes prefixed as `"robinson:"` but in fact they are **NOT** Robinson at all, but simply Packard codes. Looks as though someone did a Replace all "packard" by "robinson" but never followed through with the details. I have therefore written to the **STEP Bible** developers about this.

Meanwhile, FYI, seeing as the URL for the original key to **Robinson** morph codes is no longer found except as captured in the [Wayback Machine](https://web.archive.org/web/20160308113646/http://www.byztxt.com:80/download/PARSINGS.TXT), I hereby attach a copy FYI. This might give you an incentive to start a similar project for Robinson.

[PARSINGS.TXT](https://github.com/pierre-amadio/packard/files/6042799/PARSINGS.TXT)

**Comment by pierre-amadio** [comment]
The osis file is use comes from:
https://github.com/pierre-amadio/LXX

It does not contain all the error you mention, but it does have an error at nehemia 3:25  though:
~~~
<w lemma="strong:G511 lex:ἀνώτερος" morph="packard:A1ACNSM" xlit="betacode:A)NW/TEROS">ἀνώτερος</w>
~~~
that looks like a typo in the original text that should be corrected as A1A-NSM.

The plan is to have the current script to detect such invalid code and to correct them in the building of the LXX module.
