### ISSUE TITLE
Converting the descriptions to ThML format ?

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/packard#2]
Will your script format the TEI **def** elements with **line breaks** after each **property**?

Do you intend to add **bold text** styling for each **property** ending with a colon ?
cf. At present, only each **entryFree** **title** is bold, e.g.
```
 <entryFree sortKey="A-APM">
   <title><hi rend="bold">A-APM</hi></title>
   <def>part of speech:adjective 
declension:undefine 
case:Accusative
number:Plural 
gender:Masculine</def>
  </entryFree>
```

If so, then these can become a good basis to create a SWORD dictionary module entirely by scripting.

**Comment by pierre-amadio** [comment]
I d like to have 'raw text' first, with simple copy paste of the *Morph-Coding file.
Once this work, adding formating should not be a big problem.

**Comment by pierre-amadio** [comment]
it should work now.
