### ISSUE TITLE
Append the number of LXX occurrences for each packard code to its description?

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/packard#3]
If the **Packard** dictionary module is uniquely linked to the **LXX**, the number of occurrences for each morph code could be usefully appended to its description.

This would provide the Bible student with a measure of how _common_ or how _rare_ each morphology code was in the whole work.

**Occurrence in LXX:** `nnnn` times

**Comment by DavidHaslam** [comment]
### Interesting observation

In the **LXX** version 3.0, here are the counts for **Packard** codes that do **not** contain a hyphen!
```
Count	Packard
1	A
1	A1ACNSM
1	A1P
3	A3
74070	C
21089	D
1382	I
3357	M
38	N
54862	P
2	RI
8718	X
```
The second code in the above list seems to be an _exception_ and may possibly contain a **typo**!

**Comment by DavidHaslam** [comment]
NB. The extracted counts _include_ those in all OSIS **variants** within the **LXX** module!

**Comment by pierre-amadio** [comment]
I do not plan to add information about the number of occurences of an entry in the LXX text in the Packard description of a code. I want the description to be only about grammar.

It is already possible to get the information about the number occurences of an entry with something like

diatheke -b LXX -o avlmn -f FMT_OSIS -s phrase -k "VAI-AAI3S"
