### ISSUE TITLE
Creating a dictionary module for SWORD ?

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/packard#4]
The simplest method is to use **IMP** format with each entry having (eg) **ThML** fragments for the formatting.

NB. The entries could just as well have **TEI** or **OSIS** fragments.

**Aside:** _There are some purists that frown on this approach_.

This enables a dictionary module to be built using the Sword utility called `imp2ld`.

For an example, see my own [packard](https://git.crosswire.org/david/packard) project.

The more rigorous method is to use **TEI XML** format for the source file and then use `tei2mod` to build the module.

cf. _Maybe someone has already made a script that can convert **IMP** to **TEI**_ ?

**Comment by DavidHaslam** [comment]
This [wiki page](https://wiki.crosswire.org/Module_Submission) describes the way to submit data to CrossWire for either a new module release or an existing module update.

**Comment by DavidHaslam** [comment]
A module submission should always include a module `.conf` file.

The `.conf` file for a module update should be made by editing the previously released one.

@pierre-amadio 
_Do you have a copy of the most recent `packard.conf`_ ?

**Comment by DavidHaslam** [comment]
The **teiHeader** content should be project specific.
```
<teiHeader>
 <fileDesc>
  <titleStmt>
   <title>A title statement about the electronic text</title>
  </titleStmt>
  <publicationStmt>
   <p>Information on the publication of the electronic text.</p>
  </publicationStmt>
  <sourceDesc>
   <p>A bibliographic description of the source for the electronic text.</p>
  </sourceDesc>
 </fileDesc>
</teiHeader>
```
Please supply this and include **revisionDesc** too.

For example, this is from [another project](https://github.com/DavidHaslam/VulgateGlaire):
```
   <teiHeader>
      <fileDesc>
         <titleStmt>
            <title>Traduction de la Vulgate en français</title>
         </titleStmt>
         <publicationStmt>
            <ab>No idea yet</ab>
         </publicationStmt>
         <sourceDesc>
            <ab>Le texte de cette traduction française de la Vulgate latine a été téléchargé sur le
               site http://jesusmarie.free.fr/bible_vigouroux.html en mars 2017, et converti en TEI
               XML grâce à une série d'expressions régulières. Nota bene: la présente conversion ne
               s'est intéressée qu'au texte de la Vulgate tel que traduit par l'Abbé Glaire, en
               laissant de côté toutes les introductions, notes et commentaires. </ab>
         </sourceDesc>
      </fileDesc>
      <revisionDesc>
         <change when="2017-03-27">Converted into a TEI format proposed by Lou Burnard</change>
      </revisionDesc>
   </teiHeader>
```

**Comment by DavidHaslam** [comment]
FYI. I hereby attach a **character frequency** analysis for the downloaded TEI XML file (in **tab delimited text** format).

[packard.tei.xml.character.frequency.txt](https://github.com/pierre-amadio/packard/files/6062672/packard.tei.xml.character.frequency.txt)

The analysis was done using one of the **Tools** menu options in [BabelPad](https://www.babelstone.co.uk/Software/BabelPad.html).

**Comment by DavidHaslam** [comment]
FYI. I have just created eXperimental module **PackardX** from your initial TEI XML file.

Herein is the `.conf` file that supports it.  
[packardx.zip](https://github.com/pierre-amadio/packard/files/6068691/packardx.zip)

And herein is the **Windows CMD** file whereby I made the module. 
[Make PackardX TEI.zip](https://github.com/pierre-amadio/packard/files/6068696/Make.PackardX.TEI.zip)

I tested the module using `mod2imp` and the results are fine apart from needing to be better formatted.

The first few entries are:
```
$$$A
<entryFree sortKey="A">   <title><hi rend="bold">A</hi></title>   <def>none</def>  </entryFree>
$$$A-APM
<entryFree sortKey="A-APM">   <title><hi rend="bold">A-APM</hi></title>   <def>part of speech:adjective  declension:undefine  case:Accusative number:Plural  gender:Masculine</def>  </entryFree>
$$$A-APN
<entryFree sortKey="A-APN">   <title><hi rend="bold">A-APN</hi></title>   <def>part of speech:adjective  declension:undefine  case:Accusative number:Plural  gender:Neutral</def>  </entryFree>
$$$A-ASF
<entryFree sortKey="A-ASF">   <title><hi rend="bold">A-ASF</hi></title>   <def>part of speech:adjective  declension:undefine  case:Accusative number:Singular  gender:Feminine</def>  </entryFree>
```

I suggest you at least include an XML `<BR />` element before each _property_ in the **def** element after the first of such.

**Comment by pierre-amadio** [comment]
br does not look like a valid element in a def node:

output from xmllint complains about
```
packard.tei.xml:4096: element br: Schemas validity error : Element '{http://www.crosswire.org/2013/TEIOSIS/namespace}br': This element is not expected. Expected is one of ( {http://www.crosswire.org/2013/TEIOSIS/namespace}foreign, {http://www.crosswire.org/2013/TEIOSIS/namespace}emph, {http://www.crosswire.org/2013/TEIOSIS/namespace}distinct, {http://www.crosswire.org/2013/TEIOSIS/namespace}mentioned, {http://www.crosswire.org/2013/TEIOSIS/namespace}soCalled, {http://www.crosswire.org/2013/TEIOSIS/namespace}gloss, {http://www.crosswire.org/2013/TEIOSIS/namespace}term, {http://www.crosswire.org/2013/TEIOSIS/namespace}title, {http://www.crosswire.org/2013/TEIOSIS/namespace}code, {http://www.crosswire.org/2013/TEIOSIS/namespace}ident ).
```

I do not find a valid 'carriage return' formatting tag in the def node:
https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-def.html

**Comment by DavidHaslam** [comment]
_Mea culpa_!

I mistakenly thought that a standard **HTML** element such as `<BR />` would have been permissible almost anywhere.

_It was me getting mixed up in my old age!_  
It should be `<lb />` !
This is allowed in XML within a  **def** element.

**Comment by DavidHaslam** [comment]
I just created a simple bespoke TextPipe filter to insert line break elements `<lb />` into the TEI def elements.

I rebuilt the module and tested it in **Xiphos** as well as with `mod2imp`.

It's certainly looking better than before when each **def** text was all on one line.

Methinks the **property names** might look better if the first letter of each were Capitalised.

It would also be sensible to _italicise_ each property name, like in the existing **Robinson** dictionary module.

**Comment by pierre-amadio** [comment]
Should be fixed with the latest commit.

The only italic formatting that seems to be valid within a def node that i found is `<hi rend="italic">bla</hi>`. The xml validate, however it does not shown as italic within xiphos.
Also, the lb node are not rendered as line break in the diatheke plain outpout:

```
$ diatheke -f FMT_OSIS -b Packard -k V-PAI-3S
: <entryFree sortKey="V-IMI1P">   <title><hi rend="bold">V-IMI1P</hi></title>   <def><lb/><hi rend="italic">Part of speech:</hi>verb  <lb/><hi rend="italic">Tense:</hi>imperfect  <lb/><hi rend="italic">Voice:</hi>middle  <lb/><hi rend="italic">Mood:</hi>indicative  <lb/><hi rend="italic">Person:</hi>1  <lb/><hi rend="italic">Number:</hi>plural </def>  </entryFree>
(Packard)
$ diatheke -f plain -b Packard -k V-PAI-3S
:  V-IMI1P Part of speech:verb Tense:imperfect Voice:middle Mood:indicative Person:1 Number:plural 
(Packard)
```

**Comment by DavidHaslam** [comment]
Using TextPipe, I have just added the italics markup in my own derived TEI file and rebuilt the module.

The **Xiphos Dictionary** [view](https://www.dropbox.com/s/8dd9oezaz8o8x3q/Screenshot%202021-03-03%2010.39.52.png?dl=0) displays the italics OK.

### Notes:
1. Please ensure that the **colon** at the end of each def **property** name is followed by a single space.
2. Please also remove any spaces that immediately _precede_ the **colon**.

You probably simply need to tweak your **template** and re-run.

**Comment by DavidHaslam** [comment]
NB. The **diatheke** support for TEI based dictionary modules has probably not been adequately tested or considered until now.

It would be cool if it it did properly support the line breaks, though.

Please add an issue in the [CrossWire tracker](https://tracker.crosswire.org/) under MODTOOLS _but don't hold your breath_.

NB. If you require an account, please ask Troy.

**Comment by DavidHaslam** [comment]
Some of the entries ended up with a line break within my italics marked text.

To illustrate this, I have applied "pretty print" to the XML in this snippet.
```
			<entryFree sortKey="A1-APF">
				<title>
					<hi rend="bold">A1-APF</hi>
				</title>
				<def>
					<hi rend="italic">part of speech</hi>
					: adjective
					<lb/>
					<hi rend="italic">declension</hi>
					: 1st/2nd
					<lb/>
					<hi rend="italic">-ος -η -ον pattern endings
						<lb/>
						case
					</hi>
					: Accusative
					<lb/>
					<hi rend="italic">number</hi>
					: Plural
					<lb/>
					<hi rend="italic">gender</hi>
					: Feminine
				</def>
			</entryFree>
```

This may reflect something slightly askew in your template.

**Comment by DavidHaslam** [comment]
NB. In my "duplicating" of your improvements, I've yet to include using TextPipe the **capitalisation** of the property names.

_I'm content to wait and pick this up a bit later._

**Comment by pierre-amadio** [comment]
should be fixed.
