### ISSUE TITLE
Convert IMP format to TEI XML ?

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/packard#5]
Although a dictionary module can be made from an **IMP** file using the Sword tool `imp2ld`, it’s advisable to have **TEI XML** as the input format and use `tei2mod` for module build. 

To help implement this, it would useful to develop a script to convert **IMP** to **TEI** for dictionary data.

Has anyone already developed such a script ?

**Comment by pierre-amadio** [comment]
i dont know, i used TEI directly.
