### ISSUE TITLE
LXX morphhology codes containing a plus sign are not decoded

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/packard#7]
The following 12 morphology keys from your **LXX** text are not decoded to dictionary definitions:
```
C+D
C+RDDPM
C+RDGSM
C+RDNPM
C+RPAS
C+RPDS
C+RPGS
C+RPNS
C+RPNSM
C+X
P+A3ASM
P+X
```

Should these keys in **LXX** have the `+` replaced by `-` ?

**Comment by pierre-amadio** [comment]
They are decoded as simple conjonction since this commit 
https://github.com/pierre-amadio/packard/commit/7292b313d6a922a35e962462cfe2262fa95c3dee

Those are not documented in 

 http://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/*Morph-Coding

**Comment by DavidHaslam** [comment]
Should we not at least add "undocumented subcode" just like we have "unparsable code" for 10 other entries?
