### ISSUE TITLE
Abbreviations ought to be expanded

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/packard#8]
A case insensitive search for the **regexp** `(masc|fem|nom)\.` gave 211 hits.

IMHO, these ought to be expanded to "masculine", "feminine" and "nominative" respectively.

I see no advantage in still using such abbreviations within the **def** elements!

The full words are already in use in other places.

A case insensitive search for the **regexp** `(masculine|feminine|nominative)` gave 1925 hits.

**Comment by pierre-amadio** [comment]
I used the abbreviation used in http://ccat.sas.upenn.edu/gopher/text/religion/biblical/lxxmorph/*Morph-Coding
i like it this way because it save a bit of space which can be handy when the size left to see the definition such as the xiphos panel is small.

**Comment by DavidHaslam** [comment]
I disagree entirely. 
How things display in Xiphos should **not** be the defining criterion.
In any case, the pane/window size can easily be adjusted in Xiphos.

It also **skews search results** when sometimes a word is abbreviated and elsewhere in the majority of cases it isn't.

Moreover, for anyone whose first language is not English, the abbreviation might not be readily understood, despite the context.

**Comment by DavidHaslam** [comment]
Where some of the abbreviations are used, your argument doesn't even hold.
Here's a [screenshot](https://www.dropbox.com/s/qm3i26mxz927l19/Screenshot%202021-03-03%2021.25.13.png?dl=0) from **Xiphos** that shows "Fem." at the start of a line, 
where expanding it wouldn't cause any problem in relation to the length of other lines in the same **def** element.

Please ignore the capitalised "In." - that was an unfixed artefact of using "Sentence case" in my TextPipe filter.

**Comment by DavidHaslam** [comment]
Worse still, there are 14 instances of a **single letter abbreviation**.
```
Stem in -η, nominative in -α (F.) 
```
I didn't spot these earlier!

Are these supposed to expand to "Feminine" ?

How would a _non-native_ English speaker know that?

**Comment by DavidHaslam** [comment]
How does this work for this entry?
```
N1S-NSM
Part of speech: Noun. 
Declension: 1 
Stem in -η, nominative in -α (F.) 
Case: Nominative 
Number: Singular 
Gender: Masculine
```

If the gender is masculine, what's the "F." for ?

**Comment by DavidHaslam** [comment]
@pierre-amadio

Have you consider the comments added after you closed this issue?

**Comment by pierre-amadio** [comment]
Hi there !

It looked like i  missed some update...

For this specific one, i like it the way it is.

You may disagree, that s fine, on my side I think whoever looked at
what a declension is should understand clearly what a F means in that
context, and I do not plan to spent time on such change.

You may want to make a pull request with whatever change you think are
needed if you really think it s worth the time spent on it.

**Comment by DavidHaslam** [comment]
@pierre-amadio 

Had you considered that TEI supports abbreviations by proper XML elements?

See https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONAAB

Thus for `(F.)` you might use `(<choice><abbr>F.</abbr><expan>Feminine</expan></choice>)`

I've not looked to see to what extent (if any) the SWORD API provides any support for such a construction.

_Mouseover tooltip expansion would be cool way to do this, but then what about touch screen devices?_

cf. We do use the **abbr** element in OSIS XML and SWORD can support it IIRC.
