### ISSUE TITLE
There are 34 keys with definition = "none"

### ISSUE THREAD

**Issue by DavidHaslam** [pierre-amadio/packard#9]
Is there nothing that can be done for these 34 keys?
```
A
A1-B
A1-D
A1A-B
A1A-P
A1ACNSM
A1B-B
A1H-NSF
A1P
A3
A3H-B
A3U-B
AA-ASM
AS-ASN
ASH-NPM
M3M-ASN
M3M-NPN
N
N2C-ASM
N2C-NSM
N2E-NSM
N2M-ASN
NS-GSM
P+A3ASM
P+X
RI-D
VA-ADI2P
VFI-FAI2S
VFI-FAI3S
VI-PAI3S
VY-YAI1P
VY-YAI2S
VY-YAI3P
VYI-YAI3P
```

**Comment by DavidHaslam** [comment]
What's the difference between these and those with "code unparsable" ?

**Comment by pierre-amadio** [comment]
"unparsable code" is displayed when a noun is associated with a code that does not match the doc (see noun.py)
["A","AAN","D","G","G/D","N","S","N M","SF","SM","SN"]

For the remaining 34 one, each should be treated individually.
Ideally the task would be to:

- figure out the correct grammar form associated with word associated with those code.
- find if it can be represented with a valid code.
- if it can be represented with a valid code, it should be changed in the LXX osis file.
- if it cannot, the existing script should treat the exception as such, an exception.

This is currently not on my radar (too much time consuming for too little an effect)
Patches are welcome though.
